name: LM

on:
  schedule:
    - cron: 0 16 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Report
        run: /bin/bash ./report.sh
        env:
          LNUT_USER: ${{ secrets.LM_LNUT_USER }}
          LNUT_PASSWORD: ${{ secrets.LM_LNUT_PASSWORD }}
          NOW_ADDRESS: ${{ secrets.LM_NOW_ADDRESS }}
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: LNUT Report
          body: file://report.log
          to: ${{ secrets.LM_MAIL_ADDRESS }}
          from: ${{ secrets.MAIL_ADDRESS }}
